name: Build

on:
  push:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - '.github/*'
      - '.github/*_TEMPLATE/**'
      - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Libdragon
      run: |
           export BUILD_TAG=build-$(date -u +'%Y%m%d%H%M')
           echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
           sudo npm install -g libdragon
           sudo libdragon init
           cd libdragon
           git remote add mixer https://github.com/rasky/libdragon.git
           git fetch mixer
           git checkout mixer/mixer
           cd ..
           libdragon update
           libdragon start

    - name: Compile
      run: |
           libdragon make EP=1
           cp cosmo-engine/LICENSE LICENSE

    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      name: Create Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.BUILD_TAG }}
        prerelease: true
        files: |
               LICENSE
               *.z64
